package org.qualet.irl.light;

import com.mojang.blaze3d.opengl.GlStateManager;
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL15;
import org.lwjgl.opengl.GL21;
import org.lwjgl.opengl.GL30;
import org.lwjgl.system.MemoryUtil;

import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;

/**
 * GL owner of the bundled 128x128 R8 spatial blue-noise dither pattern
 * (void-and-cluster; generated by {@code tools/gen-blue-noise.py}, shipped as
 * {@code assets/irl-core/blue_noise_128.raw}). Registered in {@link IrlSamplers}
 * as {@code irl_blueNoise}: the injected VL march reads it with
 * {@code texelFetch(irl_blueNoise, ivec2(gl_FragCoord.xy) & 127, 0).r} when
 * flags bit2 is set (see {@link VlGlobalsBuffer}).
 *
 * <p>Lazy — no VRAM until the first {@link #getId()}, which Iris makes on the
 * render thread at sampler-bind time (GL context current). NEAREST min/mag,
 * REPEAT both wraps, uploaded exactly once. A missing or short resource logs
 * once and leaves the id at 0 — Iris then binds texture 0, the shader reads a
 * constant, and the dither quietly degrades instead of crashing.</p>
 */
public final class BlueNoiseTexture
{
    /** Square pattern size; the GLSL coordinate mask is {@code & (RES - 1)}. */
    public static final int RES = 128;

    private static final String RESOURCE = "/assets/irl-core/blue_noise_128.raw";

    private static int texId = 0;
    private static boolean attempted = false;

    private BlueNoiseTexture()
    {
    }

    /** Lazy — allocates and uploads on first call; stays 0 (inert) if the
     *  bundled resource failed to load (one attempt, logged once). */
    public static int getId()
    {
        if (!attempted)
        {
            attempted = true;
            create();
        }
        return texId;
    }

    private static void create()
    {
        byte[] raw = readResource();
        if (raw == null)
        {
            return;
        }

        // Force a clean, tightly-packed client-memory upload and restore the
        // touched state after — same rationale as CookieArrayBase.uploadLayer
        // (a PBO left bound by MC/Sodium would reinterpret our pointer as an
        // offset into that PBO and crash native; stale unpack params skew rows).
        int prevTex = GL11.glGetInteger(GL11.GL_TEXTURE_BINDING_2D);
        int prevPbo = GL11.glGetInteger(GL21.GL_PIXEL_UNPACK_BUFFER_BINDING);
        int prevAlign = GL11.glGetInteger(GL11.GL_UNPACK_ALIGNMENT);
        int prevRowLen = GL11.glGetInteger(GL11.GL_UNPACK_ROW_LENGTH);
        int prevSkipRows = GL11.glGetInteger(GL11.GL_UNPACK_SKIP_ROWS);
        int prevSkipPixels = GL11.glGetInteger(GL11.GL_UNPACK_SKIP_PIXELS);

        GL15.glBindBuffer(GL21.GL_PIXEL_UNPACK_BUFFER, 0);
        GL11.glPixelStorei(GL11.GL_UNPACK_ALIGNMENT, 1);
        GL11.glPixelStorei(GL11.GL_UNPACK_ROW_LENGTH, 0);
        GL11.glPixelStorei(GL11.GL_UNPACK_SKIP_ROWS, 0);
        GL11.glPixelStorei(GL11.GL_UNPACK_SKIP_PIXELS, 0);

        ByteBuffer pixels = MemoryUtil.memAlloc(raw.length);
        try
        {
            pixels.put(raw).flip();

            texId = GlStateManager._genTexture();
            GlStateManager._bindTexture(texId);
            GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, GL30.GL_R8, RES, RES, 0,
                GL11.GL_RED, GL11.GL_UNSIGNED_BYTE, pixels);
            GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
            GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
            GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_S, GL11.GL_REPEAT);
            GL11.glTexParameteri(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_WRAP_T, GL11.GL_REPEAT);
        }
        finally
        {
            MemoryUtil.memFree(pixels);
        }

        GlStateManager._bindTexture(prevTex);
        GL15.glBindBuffer(GL21.GL_PIXEL_UNPACK_BUFFER, prevPbo);
        GL11.glPixelStorei(GL11.GL_UNPACK_ALIGNMENT, prevAlign);
        GL11.glPixelStorei(GL11.GL_UNPACK_ROW_LENGTH, prevRowLen);
        GL11.glPixelStorei(GL11.GL_UNPACK_SKIP_ROWS, prevSkipRows);
        GL11.glPixelStorei(GL11.GL_UNPACK_SKIP_PIXELS, prevSkipPixels);
    }

    private static byte[] readResource()
    {
        try (InputStream in = BlueNoiseTexture.class.getResourceAsStream(RESOURCE))
        {
            if (in == null)
            {
                System.err.println("[irl-core] BlueNoiseTexture: bundled resource missing: " + RESOURCE);
                return null;
            }
            byte[] raw = in.readAllBytes();
            if (raw.length != RES * RES)
            {
                System.err.println("[irl-core] BlueNoiseTexture: bad resource size " + raw.length
                    + " (expected " + (RES * RES) + "): " + RESOURCE);
                return null;
            }
            return raw;
        }
        catch (IOException e)
        {
            System.err.println("[irl-core] BlueNoiseTexture: could not read " + RESOURCE + ": " + e);
            return null;
        }
    }

    /** Free the texture; the next {@link #getId()} re-creates it from the
     *  bundled resource. Deletion goes through GlStateManager so its per-unit
     *  binding cache drops the id — see SpotShadowPyramid.delete(). */
    public static void delete()
    {
        if (texId != 0)
        {
            GlStateManager._deleteTexture(texId);
            texId = 0;
        }
        attempted = false;
    }
}
